package inmorate.controlador.constants;

public final class CONSTANTS {
	public static enum GradoImportanciaEnum {MUY_IMPORTANTE, IMPORTANTE, POCO_IMPORTANTE, NADA_IMPORTANTE, SIN_DEFINIR}
	public static enum TipoSectorEnum{PAREJA_JOVEN_SIN_HIJOS, FAMILIA_2_3_HIJOS, SOLTERO, SOLTERA}
	public static enum ValoradorEnum{USUARIO, EXPERTO};
	
	// Numero identificador de cada caracteristica
	public static final int TIPO_INMUEBLE = 1;
	public static final int LUMINOSIDAD = 2;
	public static final int ORIENTACION = 3;
	public static final int REPRESENTATIVIDAD = 4;
	public static final int ESTADO_DEL_PORTAL = 5;
	public static final int FACHADA = 6;
	public static final int VISTAS = 7;
	public static final int NUMERO_HABITACIONES = 8;
	public static final int NUMERO_BANOS  = 9;
	public static final int ANTIGUEDAD  = 10;
	public static final int ALTURA  = 11;
	public static final int ASCENSOR  = 12;
	public static final int GARAJE  = 13;
	public static final int ESTADO_GENERAL  = 14;
	public static final int ZONAS_COMUNES  = 15;
	public static final int ZONA_SUBZONA  = 16;
	public static final int METROS_CONSTRUIDOS  = 17;
	public static final int METROS_HABITABLES  = 18;
	public static final int PRECIO_TASACION  = 19;
	public static final int PRECIO_SALIDA = 20;
	public static final int PRECIO_VENTA = 21;

	
	public static final int NUMERO_ELEMENTOS  = 22;
	
	//La posicion 0 no la usamos

	public static final GradoImportanciaEnum[] PAREJA_JOVEN_SIN_HIJOS = new GradoImportanciaEnum[25];
	public static final GradoImportanciaEnum[] FAMILIA_2_3_HIJOS = new GradoImportanciaEnum[25];
	public static final GradoImportanciaEnum[] SOLTERO = new GradoImportanciaEnum[25];
	public static final GradoImportanciaEnum[] SOLTERA = new GradoImportanciaEnum[25];
	
	public static final GradoImportanciaEnum[] EXPERTO_PAREJA_JOVEN_SIN_HIJOS = new GradoImportanciaEnum[25];
	public static final GradoImportanciaEnum[] EXPERTO_FAMILIA_2_3_HIJOS = new GradoImportanciaEnum[25];
	public static final GradoImportanciaEnum[] EXPERTO_SOLTERO = new GradoImportanciaEnum[25];
	public static final GradoImportanciaEnum[] EXPERTO_SOLTERA = new GradoImportanciaEnum[25];
	
	static{
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[TIPO_INMUEBLE] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[LUMINOSIDAD] = GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ORIENTACION] = GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[REPRESENTATIVIDAD] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ESTADO_DEL_PORTAL] = GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[FACHADA] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[VISTAS] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[NUMERO_HABITACIONES] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[NUMERO_BANOS] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ANTIGUEDAD] = GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ALTURA] = GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ASCENSOR] = GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[GARAJE] = GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ESTADO_GENERAL] = GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ZONAS_COMUNES] = GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[ZONA_SUBZONA] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[METROS_CONSTRUIDOS] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[METROS_HABITABLES] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[PRECIO_TASACION] = GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[PRECIO_SALIDA] = GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_PAREJA_JOVEN_SIN_HIJOS[PRECIO_VENTA] = GradoImportanciaEnum.MUY_IMPORTANTE;
    
		EXPERTO_FAMILIA_2_3_HIJOS[TIPO_INMUEBLE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[LUMINOSIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ORIENTACION]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[REPRESENTATIVIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ESTADO_DEL_PORTAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[FACHADA]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[VISTAS]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[NUMERO_HABITACIONES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[NUMERO_BANOS]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ANTIGUEDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ALTURA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ASCENSOR]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[GARAJE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ESTADO_GENERAL]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ZONAS_COMUNES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[ZONA_SUBZONA]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[METROS_CONSTRUIDOS]= GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[METROS_HABITABLES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[PRECIO_TASACION]= GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[PRECIO_SALIDA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_FAMILIA_2_3_HIJOS[PRECIO_VENTA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		
		EXPERTO_SOLTERO[TIPO_INMUEBLE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[LUMINOSIDAD]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[ORIENTACION]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[REPRESENTATIVIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[ESTADO_DEL_PORTAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[FACHADA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[VISTAS]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[NUMERO_HABITACIONES]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[NUMERO_BANOS]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[ANTIGUEDAD]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[ALTURA]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[ASCENSOR]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[GARAJE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[ESTADO_GENERAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[ZONAS_COMUNES]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[ZONA_SUBZONA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[METROS_CONSTRUIDOS]= GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_SOLTERO[METROS_HABITABLES]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERO[PRECIO_TASACION]= GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_SOLTERO[PRECIO_SALIDA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERO[PRECIO_VENTA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		
		EXPERTO_SOLTERA[TIPO_INMUEBLE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[LUMINOSIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[ORIENTACION]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[REPRESENTATIVIDAD]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERA[ESTADO_DEL_PORTAL]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERA[FACHADA]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERA[VISTAS]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[NUMERO_HABITACIONES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[NUMERO_BANOS]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERA[ANTIGUEDAD]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERA[ALTURA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[ASCENSOR]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[GARAJE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[ESTADO_GENERAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[ZONAS_COMUNES]= GradoImportanciaEnum.IMPORTANTE;
		EXPERTO_SOLTERA[ZONA_SUBZONA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[METROS_CONSTRUIDOS]= GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_SOLTERA[METROS_HABITABLES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[PRECIO_TASACION]= GradoImportanciaEnum.NADA_IMPORTANTE;
		EXPERTO_SOLTERA[PRECIO_SALIDA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		EXPERTO_SOLTERA[PRECIO_VENTA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		
		PAREJA_JOVEN_SIN_HIJOS[TIPO_INMUEBLE] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[LUMINOSIDAD] = GradoImportanciaEnum.NADA_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ORIENTACION] = GradoImportanciaEnum.NADA_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[REPRESENTATIVIDAD] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ESTADO_DEL_PORTAL] = GradoImportanciaEnum.IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[FACHADA] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[VISTAS] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[NUMERO_HABITACIONES] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[NUMERO_BANOS] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ANTIGUEDAD] = GradoImportanciaEnum.NADA_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ALTURA] = GradoImportanciaEnum.IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ASCENSOR] = GradoImportanciaEnum.NADA_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[GARAJE] = GradoImportanciaEnum.IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ESTADO_GENERAL] = GradoImportanciaEnum.IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ZONAS_COMUNES] = GradoImportanciaEnum.IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[ZONA_SUBZONA] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[METROS_CONSTRUIDOS] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[METROS_HABITABLES] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[PRECIO_TASACION] = GradoImportanciaEnum.NADA_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[PRECIO_SALIDA] = GradoImportanciaEnum.MUY_IMPORTANTE;
		PAREJA_JOVEN_SIN_HIJOS[PRECIO_VENTA] = GradoImportanciaEnum.MUY_IMPORTANTE;
    
		FAMILIA_2_3_HIJOS[TIPO_INMUEBLE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[LUMINOSIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ORIENTACION]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[REPRESENTATIVIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ESTADO_DEL_PORTAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[FACHADA]= GradoImportanciaEnum.IMPORTANTE;
		FAMILIA_2_3_HIJOS[VISTAS]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[NUMERO_HABITACIONES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[NUMERO_BANOS]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ANTIGUEDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ALTURA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ASCENSOR]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[GARAJE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ESTADO_GENERAL]= GradoImportanciaEnum.IMPORTANTE;
		FAMILIA_2_3_HIJOS[ZONAS_COMUNES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[ZONA_SUBZONA]= GradoImportanciaEnum.IMPORTANTE;
		FAMILIA_2_3_HIJOS[METROS_CONSTRUIDOS]= GradoImportanciaEnum.NADA_IMPORTANTE;
		FAMILIA_2_3_HIJOS[METROS_HABITABLES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[PRECIO_TASACION]= GradoImportanciaEnum.NADA_IMPORTANTE;
		FAMILIA_2_3_HIJOS[PRECIO_SALIDA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		FAMILIA_2_3_HIJOS[PRECIO_VENTA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		
		SOLTERO[TIPO_INMUEBLE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[LUMINOSIDAD]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[ORIENTACION]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[REPRESENTATIVIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[ESTADO_DEL_PORTAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[FACHADA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[VISTAS]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[NUMERO_HABITACIONES]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[NUMERO_BANOS]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[ANTIGUEDAD]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[ALTURA]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[ASCENSOR]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[GARAJE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[ESTADO_GENERAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[ZONAS_COMUNES]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[ZONA_SUBZONA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[METROS_CONSTRUIDOS]= GradoImportanciaEnum.NADA_IMPORTANTE;
		SOLTERO[METROS_HABITABLES]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERO[PRECIO_TASACION]= GradoImportanciaEnum.NADA_IMPORTANTE;
		SOLTERO[PRECIO_SALIDA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERO[PRECIO_VENTA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		
		SOLTERA[TIPO_INMUEBLE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[LUMINOSIDAD]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[ORIENTACION]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[REPRESENTATIVIDAD]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERA[ESTADO_DEL_PORTAL]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERA[FACHADA]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERA[VISTAS]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[NUMERO_HABITACIONES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[NUMERO_BANOS]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERA[ANTIGUEDAD]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERA[ALTURA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[ASCENSOR]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[GARAJE]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[ESTADO_GENERAL]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[ZONAS_COMUNES]= GradoImportanciaEnum.IMPORTANTE;
		SOLTERA[ZONA_SUBZONA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[METROS_CONSTRUIDOS]= GradoImportanciaEnum.NADA_IMPORTANTE;
		SOLTERA[METROS_HABITABLES]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[PRECIO_TASACION]= GradoImportanciaEnum.NADA_IMPORTANTE;
		SOLTERA[PRECIO_SALIDA]= GradoImportanciaEnum.MUY_IMPORTANTE;
		SOLTERA[PRECIO_VENTA]= GradoImportanciaEnum.MUY_IMPORTANTE;
	}

}
